-- Owner-controlled source system.
ALTER TABLE sources ADD COLUMN publication_policy TEXT NOT NULL DEFAULT 'AUTO'
  CHECK (publication_policy IN ('AUTO','VERIFY_ONLY','DISCOVERY_ONLY','NEVER_PUBLISH'));
ALTER TABLE sources ADD COLUMN priority_rank INTEGER NOT NULL DEFAULT 99;
ALTER TABLE sources ADD COLUMN polling_interval_seconds INTEGER NOT NULL DEFAULT 120;
ALTER TABLE sources ADD COLUMN source_control_state TEXT NOT NULL DEFAULT 'OWNER_ENABLED'
  CHECK (source_control_state IN ('OWNER_ENABLED','OWNER_DISABLED','DISCOVERY_ONLY','ARCHIVED'));
ALTER TABLE sources ADD COLUMN topic_mode TEXT NOT NULL DEFAULT 'ALL'
  CHECK (topic_mode IN ('ALL','PRIORITIZE_SELECTED','ONLY_SELECTED'));
ALTER TABLE sources ADD COLUMN selected_topics TEXT NOT NULL DEFAULT '';
